const text = [
	`Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
	`Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
	`Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
	`Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
	`This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
	`Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
	`Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
	`Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
	`Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
	`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis ultricies lacus sed turpis. Eleifend quam adipiscing vitae proin sagittis nisl. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Senectus et netus et malesuada fames ac turpis egestas. Lobortis elementum nibh tellus molestie nunc. Faucibus a pellentesque sit amet porttitor eget. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Eget est lorem ipsum dolor sit amet. Feugiat nibh sed pulvinar proin gravida hendrerit. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Egestas egestas fringilla phasellus faucibus.`,

	`Dictumst quisque sagittis purus sit. Turpis tincidunt id aliquet risus feugiat in ante. Consectetur adipiscing elit duis tristique. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Orci dapibus ultrices in iaculis nunc sed augue lacus. In nibh mauris cursus mattis molestie. Et malesuada fames ac turpis. Urna nunc id cursus metus aliquam eleifend mi in nulla. Vulputate sapien nec sagittis aliquam malesuada. Fermentum leo vel orci porta non pulvinar neque. Diam ut venenatis tellus in metus vulputate eu scelerisque.`,

	`Tortor at auctor urna nunc id cursus metus aliquam. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien et. Elit sed vulputate mi sit amet mauris commodo quis. Imperdiet proin fermentum leo vel orci porta non pulvinar. Felis imperdiet proin fermentum leo vel orci. Ullamcorper velit sed ullamcorper morbi tincidunt ornare. Et netus et malesuada fames ac turpis egestas sed tempus. At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Eget dolor morbi non arcu risus quis varius. Velit dignissim sodales ut eu sem integer. Donec ac odio tempor orci dapibus ultrices in iaculis. Vel turpis nunc eget lorem dolor. Eros in cursus turpis massa. Vitae congue mauris rhoncus aenean vel elit.`,

	`Dolor sit amet consectetur adipiscing. Nunc id cursus metus aliquam eleifend mi in nulla. Commodo elit at imperdiet dui. Odio euismod lacinia at quis risus sed vulputate. Mauris rhoncus aenean vel elit scelerisque. Cursus sit amet dictum sit amet. Ac feugiat sed lectus vestibulum mattis ullamcorper velit. Id diam vel quam elementum. Pulvinar proin gravida hendrerit lectus a. Pulvinar elementum integer enim neque volutpat. Lectus proin nibh nisl condimentum id. Ac orci phasellus egestas tellus rutrum tellus pellentesque.`,

	`Congue quisque egestas diam in. Aenean pharetra magna ac placerat. Tellus cras adipiscing enim eu turpis egestas. Enim tortor at auctor urna nunc. A erat nam at lectus urna duis convallis convallis. Commodo ullamcorper a lacus vestibulum sed. Dictum sit amet justo donec enim diam vulputate ut pharetra. Purus in massa tempor nec feugiat nisl pretium fusce. In fermentum et sollicitudin ac orci phasellus. Diam sollicitudin tempor id eu. Ac tincidunt vitae semper quis.`,

	`Neque laoreet suspendisse interdum consectetur libero id faucibus. Pretium fusce id velit ut tortor pretium viverra suspendisse. Etiam dignissim diam quis enim lobortis. Venenatis a condimentum vitae sapien pellentesque. Sed elementum tempus egestas sed sed risus pretium quam. Risus nec feugiat in fermentum. Fermentum dui faucibus in ornare quam viverra orci sagittis eu. Tristique magna sit amet purus gravida quis blandit turpis. Neque convallis a cras semper auctor. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Non tellus orci ac auctor augue mauris. In aliquam sem fringilla ut morbi tincidunt.`,

	`Faucibus ornare suspendisse sed nisi lacus sed. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque. Donec adipiscing tristique risus nec feugiat in. Faucibus ornare suspendisse sed nisi lacus sed. Purus non enim praesent elementum facilisis. Id interdum velit laoreet id. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Viverra orci sagittis eu volutpat odio facilisis mauris sit. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Vitae ultricies leo integer malesuada nunc vel risus. In massa tempor nec feugiat nisl pretium. Ac turpis egestas maecenas pharetra convallis posuere morbi leo. Nisl nunc mi ipsum faucibus vitae aliquet. Nec ultrices dui sapien eget. Porttitor eget dolor morbi non arcu. Eros in cursus turpis massa tincidunt. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Non blandit massa enim nec.`,

	`Donec massa sapien faucibus et. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Sed augue lacus viverra vitae congue eu consequat ac felis. Nibh sit amet commodo nulla facilisi nullam vehicula. Et malesuada fames ac turpis egestas maecenas pharetra. Quis vel eros donec ac odio tempor orci dapibus. Pharetra sit amet aliquam id diam maecenas. Eget felis eget nunc lobortis mattis aliquam. Non diam phasellus vestibulum lorem sed risus. Nunc sed velit dignissim sodales ut eu. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus.`,

	`Amet purus gravida quis blandit turpis cursus in hac habitasse. Et tortor consequat id porta nibh venenatis. Imperdiet massa tincidunt nunc pulvinar. Tortor consequat id porta nibh venenatis cras sed felis eget. Justo laoreet sit amet cursus sit. Interdum varius sit amet mattis vulputate enim nulla. In eu mi bibendum neque egestas congue quisque egestas diam. Nec dui nunc mattis enim. Donec enim diam vulputate ut. Elit duis tristique sollicitudin nibh sit amet commodo. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Viverra accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Ut eu sem integer vitae justo eget magna fermentum. Sed viverra ipsum nunc aliquet. Orci a scelerisque purus semper. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Scelerisque mauris pellentesque pulvinar pellentesque. Mauris nunc congue nisi vitae. Nulla pellentesque dignissim enim sit amet venenatis urna. Aliquam faucibus purus in massa.`,

	`Amet est placerat in egestas erat imperdiet sed euismod. Sit amet nisl purus in mollis nunc sed. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Est lorem ipsum dolor sit amet consectetur adipiscing. Cursus mattis molestie a iaculis. Semper auctor neque vitae tempus. Magna etiam tempor orci eu lobortis elementum nibh. Nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Lacinia quis vel eros donec ac odio tempor orci. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo. Ante in nibh mauris cursus mattis molestie a iaculis at. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. At urna condimentum mattis pellentesque id nibh tortor. Enim eu turpis egestas pretium aenean. Risus quis varius quam quisque id.`,
];
export default text;
